[2024-04-26 13:26:04,095][main_GenHowTo.py][line:121][INFO] the model is loaded.
[2024-04-26 13:26:05,383][main_GenHowTo.py][line:141][INFO] Loading all_action_embeds and all_tstate_embeds from saved files...
[2024-04-26 13:26:05,387][main_GenHowTo.py][line:144][INFO] Loaded all_action_embeds and all_tstate_embeds from saved files.
[2024-04-26 13:26:05,388][main_GenHowTo.py][line:179][INFO] Got all the action and state prompts embeds.
[2024-04-26 13:26:05,388][main_GenHowTo.py][line:195][INFO] Starting training...
[2024-04-26 13:26:10,053][main_GenHowTo.py][line:228][INFO] ######################
--- Logging error ---
Traceback (most recent call last):
  File "/dvmm-filer2/users/ali/anaconda3/envs/envPP/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/dvmm-filer2/users/ali/anaconda3/envs/envPP/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/dvmm-filer2/users/ali/anaconda3/envs/envPP/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/dvmm-filer2/users/ali/anaconda3/envs/envPP/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/dvmm-filer3a/users/ali/Code/vPP/main_GenHowTo.py", line 348, in <module>
    train(args)
  File "/dvmm-filer3a/users/ali/Code/vPP/main_GenHowTo.py", line 229, in train
    logger.info("# Within Epoch Stats: "+"Epoch: "+ str(epoch)+ "# batch_seen: "+ str(batrch_idd+1),
Message: '# Within Epoch Stats: Epoch: 0# batch_seen: 1'
Arguments: (' Train Loss: ', '2.120795249938965', 'time/batch: ', 4.663990497589111)
--- Logging error ---
Traceback (most recent call last):
  File "/dvmm-filer2/users/ali/anaconda3/envs/envPP/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/dvmm-filer2/users/ali/anaconda3/envs/envPP/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/dvmm-filer2/users/ali/anaconda3/envs/envPP/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/dvmm-filer2/users/ali/anaconda3/envs/envPP/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/dvmm-filer3a/users/ali/Code/vPP/main_GenHowTo.py", line 348, in <module>
    train(args)
  File "/dvmm-filer3a/users/ali/Code/vPP/main_GenHowTo.py", line 229, in train
    logger.info("# Within Epoch Stats: "+"Epoch: "+ str(epoch)+ "# batch_seen: "+ str(batrch_idd+1),
Message: '# Within Epoch Stats: Epoch: 0# batch_seen: 1'
Arguments: (' Train Loss: ', '2.120795249938965', 'time/batch: ', 4.663990497589111)
[2024-04-26 13:26:10,082][main_GenHowTo.py][line:231][INFO] ######################
[2024-04-26 13:27:11,964][main_GenHowTo.py][line:228][INFO] ######################
--- Logging error ---
Traceback (most recent call last):
  File "/dvmm-filer2/users/ali/anaconda3/envs/envPP/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/dvmm-filer2/users/ali/anaconda3/envs/envPP/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/dvmm-filer2/users/ali/anaconda3/envs/envPP/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/dvmm-filer2/users/ali/anaconda3/envs/envPP/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/dvmm-filer3a/users/ali/Code/vPP/main_GenHowTo.py", line 348, in <module>
    train(args)
  File "/dvmm-filer3a/users/ali/Code/vPP/main_GenHowTo.py", line 229, in train
    logger.info("# Within Epoch Stats: "+"Epoch: "+ str(epoch)+ "# batch_seen: "+ str(batrch_idd+1),
Message: '# Within Epoch Stats: Epoch: 0# batch_seen: 1189'
Arguments: (' Train Loss: ', '0.6771148990141032', 'time/batch: ', 0.052045348314200254)
--- Logging error ---
Traceback (most recent call last):
  File "/dvmm-filer2/users/ali/anaconda3/envs/envPP/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/dvmm-filer2/users/ali/anaconda3/envs/envPP/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/dvmm-filer2/users/ali/anaconda3/envs/envPP/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/dvmm-filer2/users/ali/anaconda3/envs/envPP/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/dvmm-filer3a/users/ali/Code/vPP/main_GenHowTo.py", line 348, in <module>
    train(args)
  File "/dvmm-filer3a/users/ali/Code/vPP/main_GenHowTo.py", line 229, in train
    logger.info("# Within Epoch Stats: "+"Epoch: "+ str(epoch)+ "# batch_seen: "+ str(batrch_idd+1),
Message: '# Within Epoch Stats: Epoch: 0# batch_seen: 1189'
Arguments: (' Train Loss: ', '0.6771148990141032', 'time/batch: ', 0.052045348314200254)
[2024-04-26 13:27:11,967][main_GenHowTo.py][line:231][INFO] ######################
[2024-04-26 13:28:14,113][main_GenHowTo.py][line:228][INFO] ######################
--- Logging error ---
Traceback (most recent call last):
  File "/dvmm-filer2/users/ali/anaconda3/envs/envPP/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/dvmm-filer2/users/ali/anaconda3/envs/envPP/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/dvmm-filer2/users/ali/anaconda3/envs/envPP/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/dvmm-filer2/users/ali/anaconda3/envs/envPP/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/dvmm-filer3a/users/ali/Code/vPP/main_GenHowTo.py", line 348, in <module>
    train(args)
  File "/dvmm-filer3a/users/ali/Code/vPP/main_GenHowTo.py", line 229, in train
    logger.info("# Within Epoch Stats: "+"Epoch: "+ str(epoch)+ "# batch_seen: "+ str(batrch_idd+1),
Message: '# Within Epoch Stats: Epoch: 0# batch_seen: 2377'
Arguments: (' Train Loss: ', '0.6531072387085475', 'time/batch: ', 0.02614448368423969)
--- Logging error ---
Traceback (most recent call last):
  File "/dvmm-filer2/users/ali/anaconda3/envs/envPP/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/dvmm-filer2/users/ali/anaconda3/envs/envPP/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/dvmm-filer2/users/ali/anaconda3/envs/envPP/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/dvmm-filer2/users/ali/anaconda3/envs/envPP/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/dvmm-filer3a/users/ali/Code/vPP/main_GenHowTo.py", line 348, in <module>
    train(args)
  File "/dvmm-filer3a/users/ali/Code/vPP/main_GenHowTo.py", line 229, in train
    logger.info("# Within Epoch Stats: "+"Epoch: "+ str(epoch)+ "# batch_seen: "+ str(batrch_idd+1),
Message: '# Within Epoch Stats: Epoch: 0# batch_seen: 2377'
Arguments: (' Train Loss: ', '0.6531072387085475', 'time/batch: ', 0.02614448368423969)
[2024-04-26 13:28:14,117][main_GenHowTo.py][line:231][INFO] ######################
[2024-04-26 13:29:16,453][main_GenHowTo.py][line:228][INFO] ######################
--- Logging error ---
Traceback (most recent call last):
  File "/dvmm-filer2/users/ali/anaconda3/envs/envPP/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/dvmm-filer2/users/ali/anaconda3/envs/envPP/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/dvmm-filer2/users/ali/anaconda3/envs/envPP/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/dvmm-filer2/users/ali/anaconda3/envs/envPP/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/dvmm-filer3a/users/ali/Code/vPP/main_GenHowTo.py", line 348, in <module>
    train(args)
  File "/dvmm-filer3a/users/ali/Code/vPP/main_GenHowTo.py", line 229, in train
    logger.info("# Within Epoch Stats: "+"Epoch: "+ str(epoch)+ "# batch_seen: "+ str(batrch_idd+1),
Message: '# Within Epoch Stats: Epoch: 0# batch_seen: 3565'
Arguments: (' Train Loss: ', '0.6442402994900231', 'time/batch: ', 0.017485551914359545)
--- Logging error ---
Traceback (most recent call last):
  File "/dvmm-filer2/users/ali/anaconda3/envs/envPP/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/dvmm-filer2/users/ali/anaconda3/envs/envPP/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/dvmm-filer2/users/ali/anaconda3/envs/envPP/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/dvmm-filer2/users/ali/anaconda3/envs/envPP/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/dvmm-filer3a/users/ali/Code/vPP/main_GenHowTo.py", line 348, in <module>
    train(args)
  File "/dvmm-filer3a/users/ali/Code/vPP/main_GenHowTo.py", line 229, in train
    logger.info("# Within Epoch Stats: "+"Epoch: "+ str(epoch)+ "# batch_seen: "+ str(batrch_idd+1),
Message: '# Within Epoch Stats: Epoch: 0# batch_seen: 3565'
Arguments: (' Train Loss: ', '0.6442402994900231', 'time/batch: ', 0.017485551914359545)
[2024-04-26 13:29:16,456][main_GenHowTo.py][line:231][INFO] ######################
[2024-04-26 13:30:18,833][main_GenHowTo.py][line:228][INFO] ######################
--- Logging error ---
Traceback (most recent call last):
  File "/dvmm-filer2/users/ali/anaconda3/envs/envPP/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/dvmm-filer2/users/ali/anaconda3/envs/envPP/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/dvmm-filer2/users/ali/anaconda3/envs/envPP/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/dvmm-filer2/users/ali/anaconda3/envs/envPP/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/dvmm-filer3a/users/ali/Code/vPP/main_GenHowTo.py", line 348, in <module>
    train(args)
  File "/dvmm-filer3a/users/ali/Code/vPP/main_GenHowTo.py", line 229, in train
    logger.info("# Within Epoch Stats: "+"Epoch: "+ str(epoch)+ "# batch_seen: "+ str(batrch_idd+1),
Message: '# Within Epoch Stats: Epoch: 0# batch_seen: 4753'
Arguments: (' Train Loss: ', '0.6395060463865104', 'time/batch: ', 0.013123736741691797)
--- Logging error ---
Traceback (most recent call last):
  File "/dvmm-filer2/users/ali/anaconda3/envs/envPP/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/dvmm-filer2/users/ali/anaconda3/envs/envPP/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/dvmm-filer2/users/ali/anaconda3/envs/envPP/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/dvmm-filer2/users/ali/anaconda3/envs/envPP/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/dvmm-filer3a/users/ali/Code/vPP/main_GenHowTo.py", line 348, in <module>
    train(args)
  File "/dvmm-filer3a/users/ali/Code/vPP/main_GenHowTo.py", line 229, in train
    logger.info("# Within Epoch Stats: "+"Epoch: "+ str(epoch)+ "# batch_seen: "+ str(batrch_idd+1),
Message: '# Within Epoch Stats: Epoch: 0# batch_seen: 4753'
Arguments: (' Train Loss: ', '0.6395060463865104', 'time/batch: ', 0.013123736741691797)
[2024-04-26 13:30:18,836][main_GenHowTo.py][line:231][INFO] ######################
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f3f9a358f70>
Traceback (most recent call last):
  File "/dvmm-filer2/users/ali/anaconda3/envs/envPP/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1479, in __del__
    self._shutdown_workers()
  File "/dvmm-filer2/users/ali/anaconda3/envs/envPP/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1443, in _shutdown_workers
    w.join(timeout=_utils.MP_STATUS_CHECK_INTERVAL)
  File "/dvmm-filer2/users/ali/anaconda3/envs/envPP/lib/python3.10/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/dvmm-filer2/users/ali/anaconda3/envs/envPP/lib/python3.10/multiprocessing/popen_fork.py", line 40, in wait
    if not wait([self.sentinel], timeout):
  File "/dvmm-filer2/users/ali/anaconda3/envs/envPP/lib/python3.10/multiprocessing/connection.py", line 931, in wait
    ready = selector.select(timeout)
  File "/dvmm-filer2/users/ali/anaconda3/envs/envPP/lib/python3.10/selectors.py", line 416, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt:
Traceback (most recent call last):
  File "/dvmm-filer3a/users/ali/Code/vPP/main_GenHowTo.py", line 348, in <module>
    train(args)
  File "/dvmm-filer3a/users/ali/Code/vPP/main_GenHowTo.py", line 221, in train
    loss.backward()
  File "/dvmm-filer2/users/ali/anaconda3/envs/envPP/lib/python3.10/site-packages/torch/_tensor.py", line 522, in backward
    torch.autograd.backward(
  File "/dvmm-filer2/users/ali/anaconda3/envs/envPP/lib/python3.10/site-packages/torch/autograd/__init__.py", line 266, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
KeyboardInterrupt